CREATE TABLE AUTORES (
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL
);

CREATE UNIQUE INDEX SYS_C008222 ON AUTORES (ID);

CREATE TABLE LIBROS (
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TITULO VARCHAR2(200) NOT NULL,
    AUTOR_ID NUMBER NOT NULL,
    CONSTRAINT FK_LIBROS_AUTORES FOREIGN KEY (AUTOR_ID) REFERENCES AUTORES(ID) ON DELETE CASCADE
);

CREATE UNIQUE INDEX SYS_C008226 ON LIBROS (ID);

CREATE OR REPLACE PROCEDURE actualizar_autor(
    p_id IN NUMBER, 
    p_nombre IN VARCHAR2
) AS
BEGIN
    UPDATE AUTORES
    SET NOMBRE = p_nombre
    WHERE ID = p_id;
END actualizar_autor;

CREATE OR REPLACE PROCEDURE actualizar_libro(
    p_id IN NUMBER, 
    p_titulo IN VARCHAR2, 
    p_autor_id IN NUMBER
) AS
BEGIN
    UPDATE LIBROS 
    SET TITULO = p_titulo, AUTOR_ID = p_autor_id 
    WHERE ID = p_id;
END actualizar_libro;

CREATE OR REPLACE PROCEDURE eliminar_autor(
    p_id IN NUMBER
) AS
BEGIN
    DELETE FROM AUTORES WHERE ID = p_id;
END eliminar_autor;

CREATE OR REPLACE PROCEDURE eliminar_libro(
    p_id IN NUMBER
) AS
BEGIN
    DELETE FROM LIBROS WHERE ID = p_id;
END eliminar_libro;

CREATE OR REPLACE PROCEDURE insertar_autor(
    p_nombre IN VARCHAR2
) AS
BEGIN
    INSERT INTO AUTORES (NOMBRE) VALUES (p_nombre);
END insertar_autor;

CREATE OR REPLACE PROCEDURE insertar_libro(
    p_titulo IN VARCHAR2, 
    p_autor_id IN NUMBER
) AS
BEGIN
    INSERT INTO LIBROS (TITULO, AUTOR_ID) VALUES (p_titulo, p_autor_id);
END insertar_libro;

CREATE OR REPLACE PROCEDURE obtener_autores(
    p_cursor OUT tipos_cursor.ref_cursor
) AS
BEGIN
    OPEN p_cursor FOR
    SELECT ID, NOMBRE FROM AUTORES;
END obtener_autores;

CREATE OR REPLACE PROCEDURE obtener_libros(
    p_cursor OUT tipos_cursor.ref_cursor
) AS
BEGIN
    OPEN p_cursor FOR
    SELECT l.ID, l.TITULO, l.AUTOR_ID, a.NOMBRE AS AUTOR_NOMBRE
    FROM LIBROS l
    JOIN AUTORES a ON l.AUTOR_ID = a.ID;
END obtener_libros;


-- cambiar los valores de application.properties dependiendo de la base de datos:
-- spring.application.name=prueba
-- spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDB1
-- spring.datasource.username=LIBROS_ADMIN
-- spring.datasource.password=12345
-- spring.datasource.driver-class-name=oracle.jdbc.OracleDriver